Update version_manager to enable easy beta build labels (...)
Future me, you can't just add `beta` inside the version:

Uploading django_letsencrypt-2.0.1.beta.20171119.204126-py2.py3-none-any.whl
HTTPError: 400 Client Error: version: Must start and end with a letter or numeral and contain only ascii numeric and '.', '_' and '-'. for url: https://test.pypi.org/legacy/
Makefile:60: recipe for target 'test-publish' failed

This script used to put ".beta." instead of ".123.", and this is why.